### ISSUE TITLE
Documentation: broken structure / table of contents

### ISSUE THREAD

**Issue by Chealer** [spring-projects/spring-data-commons#2371] opened 2021-05-06 19:57 UTC
As reported in ticket #2229, the [Spring Data JPA Reference Documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#faq)'s structure (and therefore its table of contents) has been broken (starting from section 5 _Reference Documentation_) for a while. All I can say is that the breakage happened on 2020-11-13 at the latest, and on 2020-10-09 at the earliest. I cannot see where the problem comes from as I do not know AsciiDoc, but I am guessing by elimination that the guilty commit is d18701a3290e383ce7730b6aa8b4cc5679309b57. If not, it may be something external.

**Comment by schauder** [comment] 2021-05-07 10:04
After examining the original ticket https://github.com/spring-projects/spring-data-commons/issues/2229 and the current version of the reference documentation (I clicked on every single entry in the TOC) I could find the following issues:

* There are sections without anchor. Fixed in https://github.com/spring-projects/spring-data-jpa/commit/e7cac87c2e636a7ef9cc879c64c33e101daf060b
* Clicking on a section in the TOC moves the document so that the start of that section is on the top of the screen. The highlighted section of the TOC seems to depend on what is in the middle of the screen. This can lead to the effect that after clicking on an entry in the TOC one of the following entry is highlighted and possibly even the clicked element disapearing when the highlited section is of a higher level then the selected one. An example of that is effect is Section _3.1. Dependency Management with Spring Boot_
* Probably not related to this issue: Section _5. Reference Documentation_ is empty.

Do you see any other weird effects? If so I'd need a fresh explanation.

**Comment by spring-projects-issues** [comment] 2021-05-14 10:09
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-05-21 10:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-05-21 10:07 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by Chealer** [comment] 2021-05-28 15:56
Greetings @schauder ,

> [...]
> 
> 
> Do you see any other weird effects? If so I'd need a fresh explanation.

Ticket #2229 reports a fair number of TOC-related issues. It is quite possible that more persist, but as I indicated there, I am waiting for the structure to be fixed before doing a last round and verifying that everything is fine. This ticket specifically tracks the biggest issue, which you alluded to in your last point (sections 5 and above).

**Comment by Chealer** [comment] 2021-06-23 21:08
@spring-projects-issues is any information missing to re-open this ticket?

**Comment by schauder** [comment] 2021-06-24 04:55
Yes. You mention a `fair number of TOC-related issues`. But I could find only the three mentioned in my previous comment. Two of these are fixed. So I don't know what these TOC-related issues are, or how to reproduce them.

**Comment by Chealer** [comment] 2021-06-25 14:25
> Yes. You mention a `fair number of TOC-related issues`. But I could find only the three mentioned in my previous comment. Two of these are fixed. So I don't know what these TOC-related issues are, or how to reproduce them.

@schauder this ticket is not about all TOC-related issues. This ticket is specifically about the broken structure, as you mentioned in your third point. I do not think it is a behavioral bug, but I guess it can be "reproduced" by clicking on either "5. Reference Documentation" or "7. Appendix".

**Comment by schauder** [comment] 2021-06-28 07:01
>  as you mentioned in your third point.

Do you mean the *second* point?

> Clicking on a section in the TOC moves the document so that the start of that section is on the top of the screen. The highlighted section of the TOC seems to depend on what is in the middle of the screen. This can lead to the effect that after clicking on an entry in the TOC one of the following entry is highlighted and possibly even the clicked element disapearing when the highlited section is of a higher level then the selected one. An example of that is effect is Section 3.1. Dependency Management with Spring Boot

**Comment by Chealer** [comment] 2021-06-29 21:01
> 
> 
> > as you mentioned in your third point.
> 
> Do you mean the _second_ point?
> 
> > Clicking on a section in the TOC moves the document so that the start of that section is on the top of the screen. The highlighted section of the TOC seems to depend on what is in the middle of the screen. This can lead to the effect that after clicking on an entry in the TOC one of the following entry is highlighted and possibly even the clicked element disapearing when the highlited section is of a higher level then the selected one. An example of that is effect is Section 3.1. Dependency Management with Spring Boot

No @schauder , I mean you _third_ point, which comes _last_:

> Section 5. Reference Documentation is empty.

**Comment by Chealer** [comment] 2021-07-30 22:04
@spring-projects-issues can this ticket be re-opened?

**Comment by schauder** [comment] 2021-08-10 12:44
The issue was already fixed, but I added backports.

**Comment by Chealer** [comment] 2021-09-10 21:53
Thank you @schauder
