### ISSUE TITLE
RepositoryFactorySupport#getRepository LogMessage bug

### ISSUE THREAD

**Issue by githubyong** [spring-projects/spring-data-commons#2507] opened 2021-12-08 07:30 UTC
spring-data-commons 2.4.1  org.springframework.data.repository.core.support.RepositoryFactorySupport.java line 313

```
		if (logger.isDebugEnabled()) {
			logger
					.debug(LogMessage.format("Finished creation of repository instance for {}.", repositoryInterface.getName()));
		}
```

there "Finished creation of repository instance for {}."  should be "Finished creation of repository instance for %s."

**Comment by mp911de** [comment] 2021-12-08 08:51
That's a duplicate of #2502 which is already fixed.

**Closed by mp911de** 2021-12-08 08:51 UTC
Labels: status: duplicate
