### ISSUE TITLE
getPersistentEntity method taking time on first request

### ISSUE THREAD

**Issue by luvsaxena1** [spring-projects/spring-data-commons#2556] opened 2022-02-18 16:07 UTC
**Issue Description**
We are using spring data commons version 2.4.5 in our project and we noticed from our monitoring tool that getPersistentEntity method is taking 10 - 15 sec (Screen shot attached below) specially on the first request for inserting or retrieving an object in collection.

After first request it resolves quickly until we bring new servers up. Once new servers are up, it again take similar time to to insert object in collection.

**Behavior / How to Reproduce**
Behavior we noticed, that every time new servers come up and if any particular new server receives request for inserting or retrieving an object in particular collection first time, getPersistentEntity is taking time. Same server will not take time for second and third request. 
However, if we change server for the same collection, getPersistentEntity again take time while inserting or retrieving object, if its first insertion or retrieval request of particular collection on that server.  

Let me know if you need more details. Any suggestions how we can resolve this issue ?  

![Screen Shot 2022-02-18 at 10 06 00 AM](https://user-images.githubusercontent.com/22630829/154718754-75d25c7a-cc7d-4158-b9d9-e9557985af42.png)

**Comment by mp911de** [comment] 2022-02-21 09:18
`PersistentEntity` inspection may take a bit when the class is seen for the first time. The mapping metadata for the entity and properties, that map to other entities are considered in that process. If you isolate the `MappingContext` and your domain model, can you build a reproducer that shows the same behavior?

**Comment by luvsaxena1** [comment] 2022-02-21 17:27
@mp911de  Thanks for your reply. Could give more context how to decouple these 2 ? Do I need to right custom mapper for this ?

**Comment by mp911de** [comment] 2023-09-14 12:23
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2023-09-14 12:23 UTC
Labels: status: waiting-for-triage, status: feedback-provided
