### ISSUE TITLE
Why is PersistentEntity created for types defined in CustomConversions?

### ISSUE THREAD

**Issue by meltsufin** [spring-projects/spring-data-commons#3085] opened 2024-04-24 03:30 UTC
`AbstractMappingContext.createAndRegisterProperty()` seems to always create a `PersistentEntity` for the type of the property, even if that type is registered in `CustomConversions`. Is this intended behavior? Maybe `shouldCreatePersistentEntityFor()` should check the registered converters?

**Comment by mp911de** [comment] 2024-04-24 06:46
That is the expected behavior for some type. There are two sorts of types managed by `CustomConversions`:

* Store-native ones (String, int, Date, UUID, …)
* Convertible types

Store-native types are expected to be stored as-is without further introspection as these types have atomic granularity (i.e. we cannot further decompose a String or an integer).

Convertible types are, while a converter is present, still candidates for further introspection. We support the usage of reading and/or writing types using a converter. However, in case of mapping update or query statements against such a type, just having a converter isn't sufficient as we want to apply field name mapping, inner type conversions and such against a type that has `Converter`s registered.

Zooming out a bit, a `Converter` only handles full reads/writes of a type, while query/update mapping quires additional model metadata.

Let me know whether this helps.

**Comment by meltsufin** [comment] 2024-04-24 16:22
Thanks, @mp911de. This does help, but I wonder how can we configure certain convertible types to be treated like atomic / simple types? For instance, it's pretty common for our users to have some complex class as a field type, simply to be converted to a JSON-encoded string in the database.

**Comment by mp911de** [comment] 2024-04-25 07:57
That is part of your store-specific converter setup. In Cassandra and Mongo (and many more stores) we have specific [`CassandraSimpleTypeHolder`](https://github.com/spring-projects/spring-data-cassandra/blob/9b930ed4ffe476ba75f974e975dc588e1bb1ab30/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/mapping/CassandraSimpleTypeHolder.java#L50) respective [`MongoSimpleTypes`](https://github.com/spring-projects/spring-data-mongodb/blob/48777564c9a6385d394a3b004c5badec15226c2f/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/mapping/MongoSimpleTypes.java#L51) that provide a `SimpleTypeHolder` specific to what the driver/database considers a native type. In your case, you should have a `GcpDatastoreSimpleTypeHolder` that you pass on to `CustomConversions`. 

Over time we evolved `CustomConversions` to store-specific subclasses such as [`CassandraCustomConversions`](https://github.com/spring-projects/spring-data-cassandra/blob/9b930ed4ffe476ba75f974e975dc588e1bb1ab30/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/convert/CassandraCustomConversions.java#L52) that provide a convenient API to not only set up the store-specific converter part but also any user-provided converters

**Comment by meltsufin** [comment] 2024-04-25 12:02
Our goals is to enable user-provided converters. Those converters should always map to one of the basic types supported by Datastore. We are using `DatastoreCustomConversions` for that. I don't think it ever makes sense for us to create `PersistentEntity` for these user types. What's the proper way to do that?
Here's our documentation for this functionality: https://googlecloudplatform.github.io/spring-cloud-gcp/5.1.2/reference/html/index.html#custom-types-2

**Comment by meltsufin** [comment] 2024-04-26 17:11
We currently do not override `AbstractMappingContext.shouldCreatePersistentEntityFor()`, but maybe we should. I can't seem to find a way to get the `AbstractMappingContext.simpleTypeHolder` to see types from `CustomConversions` as simple.

**Comment by mp911de** [comment] 2024-04-30 07:02
I'm closing this ticket now since there isn't anything left we can do here.

**Closed** 2024-04-30 07:02 UTC
Labels: for: stackoverflow
