### ISSUE TITLE
When have field with type LocalDateTime in Projection, get Projection type must be an interface! [DATACMNS-1847]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2260] opened 2020-12-17 10:15 UTC
**[Aiksandr](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50800)** opened **[DATACMNS-1847](https://jira.spring.io/browse/DATACMNS-1847?redirect=false)** and commented

In Spring boot 2.4.1 & 2.4.0
When use projection with field typed LocalDateTime
example
public interface Report { UUID getId(); LocalDateTime getCreateDate(); }
after fetch it from DB, get exception when try access to LocalDateTime field `getCreateDate()`

 

i made sample project, if You run it like usual Spring app, that will throw this exception
https://github.com/Aiksandr/spring-jpa-demo

{{Caused by: java.lang.IllegalArgumentException: Projection type must be an interface!
at org.springframework.util.Assert.isTrue(Assert.java:121)
at org.springframework.data.projection.ProxyProjectionFactory.createProjection(ProxyProjectionFactory.java:105)
at org.springframework.data.projection.SpelAwareProxyProjectionFactory.createProjection(SpelAwareProxyProjectionFactory.java:45)
at org.springframework.data.projection.ProjectingMethodInterceptor.getProjection(ProjectingMethodInterceptor.java:160)
at org.springframework.data.projection.ProjectingMethodInterceptor.potentiallyConvertResult(ProjectingMethodInterceptor.java:108)
at org.springframework.data.projection.ProjectingMethodInterceptor.invoke(ProjectingMethodInterceptor.java:85)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)}}

And in previews versions it works ok

 

This issue already was reproduced in spring boot issue https://github.com/spring-projects/spring-boot/issues/24528)

---

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/24528

**Issue Links:**
- [DATACMNS-1836](https://jira.spring.io/browse/DATACMNS-1836) Native projection stopped working with Java8 datetime
 (_**"duplicates"**_)

0 votes, 6 watchers

**Comment by idkw** [comment] 2021-01-20 10:23
Any news ? This is a breaking change for us too.

**Comment by idkw** [comment] 2021-01-20 10:30
Duplicate of https://github.com/spring-projects/spring-data-commons/issues/2223, should be fixed in spring boot 2.4.3 then ?

**Comment by christophstrobl** [comment] 2021-01-20 10:40
Fixed via #479 included in spring-data 2.4.3, picked up by [Spring Boot 2.4.2](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#dependency-versions-coordinates)

**Closed by christophstrobl** 2021-01-20 10:40 UTC
Labels: type: bug

**Comment by ajobra76** [comment] 2021-02-05 13:22
Since the ObjectToObjectConverter is removed one workaround whould be to wite a own ConverterService and use a @Value Annotation with Spel Expression like
@Value("#{@entityToDtoConvertingHelperService.convertObjectToObject(target)}") in the Projection interface

**Comment by sgflt** [comment] 2021-02-19 09:22
As previous comment says, conversion of custom objects is now broken.

```
interface X {
  MyObject getMyObject();
}
```

with standard `javax.persistence.AttributeConverter<MyObject, String>`,

Throws projection type must be an interface! during call of X.getMyObject().

**Comment by mp911de** [comment] 2021-02-19 09:37
Complex object conversion was never subject to the conversion service used for projections. The conversion service can adjust for slight conversions (`long` to `int`) but in no case for `String` to complex object conversion.

The underlying entity is what dictates the type that needs to be used in your projection. Alternatively, use SpEL through `@Value`.

**Comment by sgflt** [comment] 2021-02-19 09:49
Umm, the code worked in Spring Boot 2.2.10, so it was jut unintended "side effect" and we are supposed to Use `@Value` Annotation? I really liked the previous behavior that magically used JPA converter.

**Comment by sgflt** [comment] 2021-02-19 09:54
I have to clarify, the projection is used in native query.

**Comment by mp911de** [comment] 2021-02-19 09:58
Feel free to file a ticket directly against [Spring Data JPA](https://github.com/spring-projects/spring-data-jpa) along with a minimal reproducible sample so we can specifically look into that issue. JPA typically returns the appropriate result and with a sample we can trace down the cause.

**Comment by NicklasWallgren** [comment] 2021-03-12 14:58
We're still seeing this issue while trying to upgrade from spring boot 2.3.8 to 2.4.3. 

The projection in question includes two `LocalDateTime` fields, and is backed by a named query.

**Comment by NicklasWallgren** [comment] 2021-03-14 11:38
@mp911de 

The issue in my case particular case was that the column property was defined as `ZonedLocalDateTime` in the entity, and the `Projection` for the same field was defined as `LocalDateTime`. The error was a bit misleading (Projection type must be an interface), and the conversion from ZonedDateTime to LocalDateTime in projections worked in 2.3.

I don't know if this can be considered as a bug or not, since it worked in 2.3.

**Comment by schauder** [comment] 2021-03-15 06:27
@NicklasWallgren please open a new issue, since this on e is closed.
