### ISSUE TITLE
createdAt field annotated with @CreationDate gets updated when an entity is modified. [using spring boot 3.0.4]

### ISSUE THREAD

**Issue by isatishp** [spring-projects/spring-data-commons#2788] opened 2023-03-07 11:04 UTC
When an entity is modified, we see that created time gets updated. This happens with newly created entity, for older entities it works fine. 

Steps to reproduce:

1. Create an entity which has fields annotated with @CreatedDate @ModifiedDate and @EntityListeners(AuditingEntityListener.class)
2. Save the entity using JPA Repository class
3. Update the entity 
4. And, you see updated entity has creationDate from the future

**Comment by mp911de** [comment] 2023-03-07 13:33
Looks like a duplicate of spring-projects/spring-data-jpa#2844.

**Closed by mp911de** 2023-03-07 13:33 UTC
Labels: status: waiting-for-triage

**Comment by isatishp** [comment] 2023-03-07 19:28
Hi I tried an example using embedded DB and I could not reproduce this issue with in memory DB. However, the moment I switched to Postgres which is also the db we use, I could reproduce the issue.. Unfortunately I do not know how to do an implementation with Test Containers.. But I have a working example here that reproduces the issue.

https://github.com/isatishp/student-crud
