### ISSUE TITLE
Table of contents sometimes locates in wrong section (confusion between subsections without id-s) [DATACMNS-1814]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#2229] opened 2020-10-09 16:55 UTC
**[Chealer](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50525)** opened **[DATACMNS-1814](https://jira.spring.io/browse/DATACMNS-1814?redirect=false)** and commented

The table of contents at the left of the Spring Data JPA Reference Documentation dynamically changes to reflect the precise subsection being shown. The subsections of sections not displaying do not display.

 

The mechanism to detect position in the document appears to be malfunctioning, as I realized that moving forward in the document, the ToC would indicate the opposite. This happened when I was going from section 4 to section 5.

 

When displaying the end of 4.8.3 and the beginning of 5, the ToC correctly contains:
1. [Preface](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#preface)
   1. [1. Project Metadata](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#project)
   2. [2. New & Noteworthy](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#new-features)
   3. [3. Dependencies](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#dependencies)
   4. [4. Working with Spring Data Repositories](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories)
      1. [4.1. Core concepts](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.core-concepts)
      2. [4.2. Query methods](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods)
      3. [4.3. Defining Repository Interfaces](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.definition)
      4. [4.4. Defining Query Methods](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.details)
      5. [4.5. Creating Repository Instances](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.create-instances)
      6. [4.6. Custom Implementations for Spring Data Repositories](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations)
      7. [4.7. Publishing Events from Aggregate Roots](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.domain-events)
      8. [4.8. Spring Data Extensions](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.extensions)

#### [4.8.3. Repository Populators](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.repository-populators)

1. [Reference Documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#reference)
   1. [5. JPA Repositories](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.repositories)
2. [Appendix](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#appendix)
   1. [Appendix A: Namespace reference](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.namespace-reference)
   2. [Appendix B: Populators namespace reference](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#populator.namespace-reference)
   3. [Appendix C: Repository query keywords](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-keywords)
   4. [Appendix D: Repository query return types](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-return-types)
   5. [Appendix E: Frequently Asked Questions](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#faq)
   6. [Appendix F: Glossary](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#glossary)

But after pressing Page down, it displays as if I had went back to 4.5.1:
1. [Preface](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#preface)
   1. [1. Project Metadata](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#project)
   2. [2. New & Noteworthy](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#new-features)
   3. [3. Dependencies](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#dependencies)
   4. [4. Working with Spring Data Repositories](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories)
      1. [4.1. Core concepts](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.core-concepts)
      2. [4.2. Query methods](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods)
      3. [4.3. Defining Repository Interfaces](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.definition)
      4. [4.4. Defining Query Methods](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.details)
      5. [4.5. Creating Repository Instances](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.create-instances)

#### [4.5.3. Standalone usage](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.create-instances.standalone)

    1. [4.6. Custom Implementations for Spring Data Repositories](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations)
    1. [4.7. Publishing Events from Aggregate Roots](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.domain-events)
    1. [4.8. Spring Data Extensions](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.extensions)

1. [Reference Documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#reference)
   1. [5. JPA Repositories](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.repositories)
2. [Appendix](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#appendix)
   1. [Appendix A: Namespace reference](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.namespace-reference)
   2. [Appendix B: Populators namespace reference](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#populator.namespace-reference)
   3. [Appendix C: Repository query keywords](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-keywords)
   4. [Appendix D: Repository query return types](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-return-types)
   5. [Appendix E: Frequently Asked Questions](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#faq)
   6. [Appendix F: Glossary](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#glossary)

 

This happens whether using Google Chrome 85 or Firefox 81, -but only when the viewport is sufficiently high. This can happen at 1153 pixels of height, but probably not when just a little less-. The difference between the Spring ToC correct and Spring ToC incorrect screenshots is exactly one Page Up/Down.

It should also be noted that the link for Using filters (in 4.5.1) is broken (it brings to the document's start)

---

**Affects:** 2.3.4 (Neumann SR4)

**Reference URL:** https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.repository-populators

**Attachments:**
- [Spring ToC correct.png](https://jira.spring.io/secure/attachment/28823/Spring+ToC+correct.png) (_206.18 kB_)
- [Spring ToC incorrect.png](https://jira.spring.io/secure/attachment/28822/Spring+ToC+incorrect.png) (_242.29 kB_)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-commons/pull/470

**Backported to:** [2.3.5 (Neumann SR5)](https://github.com/spring-projects/spring-data-commons/milestone/200?closed=1), [2.2.11 (Moore SR11)](https://github.com/spring-projects/spring-data-commons/milestone/199?closed=1)

**Comment by Chealer** [comment] 2020-12-30 12:50
Can someone with the necessary permission remove "Status: closed" from this ticket?

**Comment by mp911de** [comment] 2020-12-30 15:34
That issue should be addressed since the last release. Does it still persist for you @Chealer?

**Comment by schauder** [comment] 2021-01-04 06:23
The subsection "Custom Namespace Attributes" still has issues, probably caused by a missing anchor. 

Clicking on it in the TOC  currently jumps to the beginning of the documentation. But I'm assuming this is more of a Spring Data JPA issue. I'll open a ticket there. 

I also reopened the ticket here since @Chealer basically stated that it isn't fixed yet for him. Although we still need more information if more is broken than what I mentioned above.

**Comment by Chealer** [comment] 2021-01-22 17:59
@mp911de  I am skeptical that this issue in its wide sense is fixed as to my knowledge nothing changed in Tocbot. Specific instances (the ones I initially reported) have been worked around.

I would be happy to check where things stand, but at this time I am afraid the regression I reported on 2020-11-13 persists, and it would be simpler to verify if that was fixed. Does someone know how to reach Jay Bryant so he could check? Or should I just report a new issue?

Thank you for the followup Jens

**Comment by mp911de** [comment] 2021-01-25 09:35
It sounds as if there are two separate issues:

* TOC jumping wildly in Chrome
* TOC shows consistently wrong section

The first issue was a rendering optimization for chrome that was fixed with upgrading to a newer Spring Doc resources version.

The second issue is caused by missing anchors. Tocbot requires anchors to synchronize with the TOC and if a particular store module contains headers without an anchor, then the second issue occurs.

Do you have further references @Chealer which module and which section is affected so we can address that problem?

Paging also @Buzzardo.

**Comment by Chealer** [comment] 2021-04-28 21:54
@mp911de it is getting harder to follow this problem as the TOC (not to say the actual structure) remains broken, and the situation has evolved. It appears like most of the sections which exposed the problem now have identifiers.

By the way, I do not really understand the issues you describe. I do not know about the Spring Doc resources upgrade you refer to, but the wild TOC position jumps issue was not Chrome-specific (Firefox was/is equally affected).

That being said, appendix E still exposes the issue.

**Comment by mp911de** [comment] 2021-04-29 12:28
We fixed the issue in Spring Data JPA. Since we consider this issue now complete (the Chrome issue was addressed through https://github.com/spring-projects/spring-data-build/issues/1303), we're closing this ticket now. For future problems, please file tickets in the individual store modules that might miss anchors.

**Closed by mp911de** 2021-04-29 12:28 UTC
Labels: type: bug, type: documentation

**Comment by Chealer** [comment] 2021-05-06 20:06
I've reported the breakage in ticket #2371. I'll wait until that has been solved before coming back to this issue.

**Comment by Chealer** [comment] 2021-09-10 22:37
#2371 was solved. I do not know if Tocbot was fixed, but I now checked and if the bug remains, I could not see it exposed anywhere.
