### ISSUE TITLE
Add 'insert' method to CrudRepository

### ISSUE THREAD

**Issue by vab2048** [spring-projects/spring-data-commons#2565] opened 2022-03-01 12:55 UTC
Currently with Spring Data JDBC, when you use the 'save' method on the repository to insert a new entity with the ID set it does not work (see https://spring.io/blog/2021/09/09/spring-data-jdbc-how-to-use-custom-id-generation which gives four workarounds for this problem).

The way I currently get around this issue is by using the `JdbcAggregateTemplate`. Something like this:

```java
class A {
   private JdbcAggregateTemplate jdbcAggregateTemplate;
   private SomeRepository repository;

  void create(E entity) {
      var e = new E( /* with fields including ID */ );
      jdbcAggregateTemplate.insert(e);
  }
}
```

Then for updates I can use the `repository.save()` method.

This GitHub issue is to float the idea of having a 'create' or 'insert' method directly on the repository so that this situation can be handled without having to resort to injecting a `JdbcAggregateTemplate`.

What do you think - not worth it? Maybe worth it?

**Comment by schauder** [comment] 2022-03-01 14:26
Duplicate of spring-projects/spring-data-relational/issues/507

**Closed by schauder** 2022-03-01 14:26 UTC
Labels: status: waiting-for-triage
