### ISSUE TITLE
spring-data-commons-2.4.6 issue with PageRequest.of(0, 3)

### ISSUE THREAD

**Issue by gpamitranjit** [spring-projects/spring-data-commons#2343] opened 2021-03-29 13:56 UTC
in spring-data-commons-2.4.6 version the PageRequest.of(pageNumber, pageSize) doesn't allow me to create Page with zero index.

**Comment by mp911de** [comment] 2021-03-29 14:13
Thank you for reaching out. We have currently a hard time understanding the issue and the message you want to convey. What typically helps in these situations is spending some time describing the context, your expectation, and how these do not match. Stack traces or error messages are usually a good starting point.

Dropping a one-liner lets us assume no (or at least minimal) interest in this topic and that makes it difficult to justify spending time on this issue. We understand that language can impose barriers. To lower this barrier, please refer to [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) including its translations into other languages.

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2021-04-05 14:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-04-12 14:15
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-04-12 14:15 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
